CREATE TRIGGER checkGradeFound
AFTER INSERT ON Registered
FOR EACH ROW
EXECUTE PROCEDURE haveGrade();

CREATE TRIGGER checkOverCapacity
AFTER INSERT ON Registered
FOR EACH ROW
EXECUTE PROCEDURE limitedCapacity();